### ISSUE TITLE
paraview post processing problem

### ISSUE THREAD

**Issue by stannnnnnnnn** [ECP-WarpX/WarpX#3525]
Hi,

Thanks for your open source work! I tried to use paraview for post-processing, but both h5 and plt files got errors when opened using paraview.I tried paraview 5.6-5.10, but the problem still exists.🤦‍♂️

Looking forward to your reply!
![2KH$ZUCPDEJYUQWU3OM{ VH](https://user-images.githubusercontent.com/95198018/201815477-68b4c32c-5a73-47f4-aa8d-bbaec68347bb.png)
![}T7SXKP05_603O83(CDOQ_R](https://user-images.githubusercontent.com/95198018/201815480-f2687f25-aaa8-4a20-8d09-73f37e38a4c2.png)

**Comment by stannnnnnnnn** [comment]
[plt_file.zip](https://github.com/ECP-WarpX/WarpX/files/10008801/plt_file.zip)
[h5_file.zip](https://github.com/ECP-WarpX/WarpX/files/10008804/h5_file.zip)
This is the file I'm trying to process by running it through warpx.

**Comment by ax3l** [comment]
Hi @stannnnnnnnn,

Glad you like our work! Thanks for your report.

For ParaView, [please use the 5.11 release](https://www.paraview.org/download/). We fixed a series of issues in ParaView 5.10 and again 5.11 that are the problem you see in your 5.9.1 version with our `.pmd` file for openPMD reading (h5 or bp files supported).

**Comment by stannnnnnnnn** [comment]
hi，
Glad to receive your reply! I tried paraview5.11 and the problem wasn't completely fixed. I opened the h5 file and the plt file in the official test file of paraview5.11, and there were errors.I will use other software for post-processing work.
Wish everything goes well with your work!
![I~2{FEHL)VIK8_CVAB (I A](https://user-images.githubusercontent.com/95198018/202650781-307752e8-85f3-4d4b-ab25-81d3e7a79d19.png)
