### ISSUE TITLE
Missing particles in BTD output

### ISSUE THREAD

**Issue by RevathiJambunathan** [ECP-WarpX/WarpX#4193]
This is an issue reported by @joshualudwig8 

A simulation performed by them have strips of particles missing from the BTD output

![Screenshot 2023-08-16 at 11 34 04 AM](https://github.com/ECP-WarpX/WarpX/assets/41089244/4069a911-1c3d-480a-9ee6-58d399df7c0b)
![Screenshot 2023-08-16 at 11 34 38 AM](https://github.com/ECP-WarpX/WarpX/assets/41089244/518389d5-0940-4748-b978-35421e3c76f5)
![Screenshot 2023-08-16 at 11 35 15 AM](https://github.com/ECP-WarpX/WarpX/assets/41089244/433bd813-8851-4446-aa1e-a23c88a2e02c)

@jlvay was able to reproduce a similar error with a reduced number of snapshots (41 snapshots) on summit
![Screenshot 2023-08-16 at 11 36 29 AM](https://github.com/ECP-WarpX/WarpX/assets/41089244/6d487b1c-a9d9-4189-b63f-f291eb6d24d7)

**Comment by RevathiJambunathan** [comment]
Update so far : 
1. I first changed the output format to plotfile instead of openpmd and the code crashed with an ASSERT 
![Screenshot 2023-08-11 at 5 01 06 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/a6b4f608-4601-422e-9c0d-3f872a2c23d2)
Looking into this further -- it became clear that the input has ionization turned on and `ionization_level` is a runtime particle attribute added as a result 
However, for BTD we do not copy this attribute (we only copy/store position, momenta and particle weight) 
So I fixed this such that we do not write the ionization level and its not included in the output consistent with the implementation


2. The number of box-arrays was assumed to be 1, but in some cases where the non-moving window direction had more cells than buffer-size, we would have to boxes in a box-array. 
This is a minor detail and is now fixed. 

More to investigate as the code crashes when writing particles with plotfile format

**Comment by RevathiJambunathan** [comment]
https://github.com/ECP-WarpX/WarpX/pull/4228 
With this PR, the code does not crash with plotfile output on summit. I used @jlvay's modified input file with 41 snapshots 

here is the electrons in red : 
![Screenshot 2023-08-24 at 1 51 07 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/1423aa98-0e39-478e-8b6e-2b977f5b8d43)

ions in red
![Screenshot 2023-08-24 at 1 51 34 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/bfe58d5c-bb5c-4d3b-8dec-0a475e4d10f9)

and electrons_N  

![Screenshot 2023-08-24 at 1 51 59 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/0c909e14-c934-4da8-8de7-1184da859495)

**Comment by RevathiJambunathan** [comment]
with OpenPMD the code now crashes with a segfault on summit due to compiler issues - which is also seen with milestone runs

**Comment by ax3l** [comment]
X-ref: https://github.com/AMReX-Codes/amrex/pull/3510

**Comment by ax3l** [comment]
@RevathiJambunathan 
> However, for BTD we do not copy this attribute (we only copy/store position, momenta and particle weight)
So I fixed this such that we do not write the ionization level and its not included in the output consistent with the implementation

Would it be easy to keep the runtime attributes in BTD as well? (maybe as a follow-up)?

**Comment by ax3l** [comment]
@RevathiJambunathan the above error, did @joshualudwig8 see the particle holes w/ HDF5 openPMD files?

I assume this is not fixed by #4228?

**Comment by RevathiJambunathan** [comment]
There are two bug-fix PRs related to this issue 
#4208 and #4228 
- #4228 is related to plotfile 
- #4208 would affect both. I am currently running this input on perlmutter to check if we still see particles missing

**Comment by RevathiJambunathan** [comment]
Here are the openPMD results on perlmutter 
there are no missing particles anymore
![Screenshot 2023-08-24 at 4 06 26 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/c16bde3f-c1c3-4f96-a350-22dd75758687)
![Screenshot 2023-08-24 at 4 06 35 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/e88c3e46-6c4c-4f45-8c57-5feb6a1d2dfc)
![Screenshot 2023-08-24 at 4 06 44 PM](https://github.com/ECP-WarpX/WarpX/assets/41089244/a519ccd5-b61a-49d1-bc66-5cfec4bb22d9)

**Comment by RevathiJambunathan** [comment]
@joshualudwig8 we dont see any missing particles anymore

Would you be able to run your input again and see whether the issue persists?

**Comment by joshualudwig8** [comment]
Yes, I have a job in the queue on Lassen that will be relevant to this. 
I switched the output to adios because my jobs are freezing on the first snapshot when I use hdf5, do you think this could be related? They always freeze on the last buffer of snapshot 0
```
2: 0: --- INFO    : Writing buffer 65 of 65 to snapshot 0 to openPMD BTD diags/diag1
2: 0: --- INFO    : Finished writing snapshot 0 in openPMD BTD diags/diag1
```

**Comment by RevathiJambunathan** [comment]
@ax3l could this be related to the summit crashes we have been seeing?

**Comment by joshualudwig8** [comment]
Sorry my test was somewhat inconclusive. I successfully ran the simulation with adios at a lower particle count, but I also tested it again with hdf5 at the lower particle count and it also successfully ran.

**Comment by RevathiJambunathan** [comment]
Thank you for testing this @joshualudwig8 ! 
I will close this issue then!
